services:

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 admin password123; do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;
      mc mb --ignore-existing local/warehouse;
      echo 'Bucket warehouse is ready.';
      "
    restart: "no"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: pgs_user
      POSTGRES_PASSWORD: pgs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  nessie:
    image: ghcr.io/projectnessie/nessie:0.106.0
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      nessie.version.store.type: JDBC
      quarkus.datasource.db-kind: postgresql
      quarkus.datasource.username: nessie
      quarkus.datasource.password: nessie
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/nessie
    depends_on:
      - postgres
  
  trino:
    image: trinodb/trino:481
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/config.properties:/etc/trino/config.properties
      - ./trino/jvm.config:/etc/trino/jvm.config
    depends_on:
      - nessie
      - minio

volumes:
  postgres_data:
  minio_data: