#single node install config
coordinator=true
node-scheduler.include-coordinator=true
discovery.uri=http://localhost:8080
catalog.management=${ENV:CATALOG_MANAGEMENT}

query.max-memory=4GB
query.max-memory-per-node=3GB
spill-enabled=true
spiller-spill-path=/tmp/trino-spill