#single node install config
coordinator=true
node-scheduler.include-coordinator=true
discovery.uri=http://localhost:8080
catalog.management=${ENV:CATALOG_MANAGEMENT}

task.concurrency=2
query.max-memory=5GB
query.max-memory-per-node=5GB
spill-enabled=true
spiller-spill-path=/tmp/trino-spill
spiller-max-used-space-threshold=0.8