[project]
name = "lake-forge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.2",
    "loguru>=0.7.3",
    "tpchgen-cli>=2.0.2",
]

[dependency-groups]
dev = [
    "pyrefly>=0.64.1",
    "ruff>=0.15.12",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
